### ISSUE TITLE
Create BookingSystem

### ISSUE THREAD

**Issue by cyqjoseph** [AY2324S2-CS2103T-W11-3/tp#34] opened 2024-03-07 08:10 UTC
- [ ] Create BookingSystem class
- [ ] Integrate Add functionality to BookingSystem
- [ ] Integrate Delete functionality to BookingSystem

**Comment by jerremyng** [comment] 2024-03-12 06:51
Duplicate of #36

**Closed by jerremyng** 2024-03-12 06:51 UTC
